# Generated by Django 4.2.4 on 2023-08-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("table", models.CharField(max_length=255)),
                ("column", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classificacions",
            },
        ),
        migrations.CreateModel(
            name="DatabaseConnections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Database Connection",
                "verbose_name_plural": "Database Connections",
            },
        ),
        migrations.CreateModel(
            name="InformationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("regex", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Information type",
                "verbose_name_plural": "Information types",
            },
        ),
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "clasification",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="scan_history",
                        to="api_challenge.classification",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classification",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification",
                to="api_challenge.databaseconnections",
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="information_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="classification",
                to="api_challenge.informationtype",
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
