# Generated by Django 4.2.4 on 2023-08-13 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_challenge", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DatabaseConnections",
            new_name="Database",
        ),
        migrations.AlterModelOptions(
            name="scanhistory",
            options={
                "verbose_name": "Scan History",
                "verbose_name_plural": "Scans Historys",
            },
        ),
        migrations.RemoveField(
            model_name="classification",
            name="column",
        ),
        migrations.RemoveField(
            model_name="classification",
            name="database",
        ),
        migrations.RemoveField(
            model_name="classification",
            name="information_type",
        ),
        migrations.RemoveField(
            model_name="classification",
            name="table",
        ),
        migrations.RemoveField(
            model_name="classification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="scanhistory",
            name="clasification",
        ),
        migrations.AddField(
            model_name="classification",
            name="scan_history",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="classification",
                to="api_challenge.scanhistory",
            ),
        ),
        migrations.AddField(
            model_name="scanhistory",
            name="database",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="scan_history",
                to="api_challenge.database",
            ),
        ),
        migrations.AddField(
            model_name="scanhistory",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="scan_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TableDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "clasification",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="table_database",
                        to="api_challenge.classification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table database",
                "verbose_name_plural": "Tables database",
            },
        ),
        migrations.CreateModel(
            name="ColumnDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "information_type",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="column_database",
                        to="api_challenge.informationtype",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_database",
                        to="api_challenge.tabledatabase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column Database",
                "verbose_name_plural": "Columns Databases",
            },
        ),
    ]
