# Generated by Django 4.2.4 on 2023-08-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_challenge", "0002_rename_databaseconnections_database_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
