# Generated by Django 4.2.4 on 2023-08-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_challenge", "0005_alter_columndatabase_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columndatabase",
            name="information_type",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="column_database",
                to="api_challenge.informationtype",
            ),
        ),
    ]
