# Generated by Django 4.2.4 on 2023-08-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_challenge", "0006_alter_columndatabase_information_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="scan_history",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification",
                to="api_challenge.scanhistory",
            ),
        ),
    ]
