# Generated by Django 4.2.4 on 2023-08-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_challenge", "0007_alter_classification_scan_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabledatabase",
            name="clasification",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_database",
                to="api_challenge.classification",
            ),
        ),
    ]
